# Título y descripción de tu portafolio
title: Matías Zieleniec | Matemática y Computación
description: Mi portafolio de proyectos y habilidades.

# Aquí le dices a Jekyll qué tema usar
theme: jekyll-theme-minimal
