# Título y descripción de tu portafolio
title: "Matías Zieleniec | Matemática y Computación"
description: "Mi portafolio de proyectos y habilidades."

logo: /assets/profile.jpeg

# Aquí le dices a Jekyll qué tema usar
theme: jekyll-theme-minimal

# ----------------------------------------------------

# Configuración de Google Fonts
google_fonts:
  - name: "Montserrat"
    weights: "700"
  - name: "Lato"
    weights: "400,700"
